/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;
import logica.SistemaTienda;
import javax.swing.*;
import java.awt.*;
import logica.SistemaTienda;
import entidades.Producto;
import entidades.Cliente;

/**
 *
 * @author garf2
 */
public class VistaPrincipal extends BaseFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal(SistemaTienda st) {
        super(st);
        initComponents();
        setLocationRelativeTo(null);
        cargarCatalogoProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LblJoin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Pori Store");
        setBackground(new java.awt.Color(255, 0, 51));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 960));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/carro.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/logo.png"))); // NOI18N
        jLabel2.setText("jLabel1");

        LblJoin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fotos/user.png"))); // NOI18N
        LblJoin.setText("jLabel1");
        LblJoin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LblJoin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblJoinMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("PoriStore");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Inicio");

        jLabel6.setBackground(new java.awt.Color(153, 153, 153));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Categorías");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(251, 251, 251)
                .addComponent(jLabel5)
                .addGap(155, 155, 155)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 360, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblJoin, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(363, Short.MAX_VALUE))
        );

        jPanel6.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        Carrito vistaCarrito = new Carrito(st);
        vistaCarrito.setVisible(true);
        this.dispose();
        setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void LblJoinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblJoinMouseClicked
       // Si no hay sesión activa, abrir login
       if (!logica.GestorSesion.haySesionActiva()) {
           VistaLogin login = new VistaLogin(st);
           this.dispose();
           login.setVisible(true);
           login.setLocationRelativeTo(null);
       } else {
           // Si ya hay sesión, mostrar menú con opciones
           Cliente clienteActual = logica.GestorSesion.getClienteActual();
           String[] opciones = {"Ver Perfil", "Cerrar Sesión"};
           int opcion = javax.swing.JOptionPane.showOptionDialog(
               this,
               "Sesión activa: " + clienteActual.getNombre(),
               "Mi Cuenta",
               javax.swing.JOptionPane.DEFAULT_OPTION,
               javax.swing.JOptionPane.INFORMATION_MESSAGE,
               null,
               opciones,
               opciones[0]
           );

           if (opcion == 0) {
               // Ver Perfil
               javax.swing.JOptionPane.showMessageDialog(this,
                   "Nombre: " + clienteActual.getNombre() + "\n" +
                   "RUT: " + clienteActual.getRut() + "\n" +
                   "Correo: " + clienteActual.getCorreo(),
                   "Mi Perfil",
                   javax.swing.JOptionPane.INFORMATION_MESSAGE
               );
           } else if (opcion == 1) {
               // Cerrar Sesión con GestorSesion
               logica.GestorSesion.cerrarSesion();
               javax.swing.JOptionPane.showMessageDialog(this, "Sesión cerrada exitosamente");
               // Recargar vista sin sesión
               vistas.VistaPrincipal vista = new vistas.VistaPrincipal(st);
               this.dispose();
               vista.setVisible(true);
               vista.setLocationRelativeTo(null);
           }
       }  
    }//GEN-LAST:event_LblJoinMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        st.guardarDatos();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblJoin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables



    public class PanelProducto extends JPanel {

           public PanelProducto(Producto p) {
           this.setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
           this.setBackground(new Color(30, 30, 30)); // Color de la tarjeta
           this.setOpaque(true); // <--- OBLIGATORIO PARA QUE PINTE EL FONDO OSCURO
           this.setBorder(BorderFactory.createLineBorder(new Color(200, 0, 0), 1));
           this.setMaximumSize(new Dimension(160, 210));
           this.setPreferredSize(new Dimension(160, 210));

            
            JLabel lblImagen = new JLabel();
            JLabel lblNombre;
            JLabel lblPrecio;
            JButton btnAgregar = new JButton("Agregar");

            // IMAGEN
            lblImagen.setAlignmentX(Component.CENTER_ALIGNMENT);
            lblImagen.setHorizontalAlignment(SwingConstants.CENTER);
            boolean imagenCargada = false;

            if (p.getRutaImagen() != null && !p.getRutaImagen().trim().isEmpty()) {
                try {
                    java.io.File file = new java.io.File(p.getRutaImagen());
                    if (file.exists()) {
                        ImageIcon icon = new ImageIcon(file.getAbsolutePath());
                        Image img = icon.getImage().getScaledInstance(120, 90, Image.SCALE_SMOOTH);
                        lblImagen.setIcon(new ImageIcon(img));
                        imagenCargada = true;
                    }
                } catch (Exception e) {
                    imagenCargada = false;
                }
            }

            if (!imagenCargada) {
                lblImagen.setText("Sin Imagen");
                lblImagen.setForeground(Color.GRAY);
            }

            // NOMBRE DEL PRODUCTO
            String textoNombre = (p.getNombre() != null && !p.getNombre().isEmpty()) ? p.getNombre().toUpperCase() : "PRODUCTO";
            lblNombre = new JLabel(textoNombre);
            lblNombre.setFont(new Font("Segoe UI", Font.BOLD, 12));
            lblNombre.setForeground(Color.WHITE);
            lblNombre.setAlignmentX(Component.CENTER_ALIGNMENT);

            // PRECIO
            lblPrecio = new JLabel("$" + String.format("%.0f", p.getPrecio()));
            lblPrecio.setFont(new Font("Segoe UI", Font.BOLD, 13));
            lblPrecio.setForeground(new Color(255, 50, 50));
            lblPrecio.setAlignmentX(Component.CENTER_ALIGNMENT);

            // BOTON
            btnAgregar.setFont(new Font("Segoe UI", Font.BOLD, 10));
            btnAgregar.setBackground(new Color(180, 0, 0));
            btnAgregar.setForeground(Color.WHITE);
            btnAgregar.setFocusPainted(false);
            btnAgregar.setAlignmentX(Component.CENTER_ALIGNMENT);

            // COMPONENTES PARA EL PANEL
            add(Box.createVerticalStrut(10));
            add(lblImagen);
            add(Box.createVerticalStrut(10));
            add(lblNombre);
            add(Box.createVerticalStrut(10));
            add(lblPrecio);
            add(Box.createVerticalStrut(10));
            add(btnAgregar);
            add(Box.createVerticalStrut(10));
        }
    }

public void cargarCatalogoProductos() {
    jPanel6.removeAll(); //LIMPIA EL CATALOGO
    jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 15)); // ORGANIZA LAS TARJETAS
    jPanel6.setBackground(new java.awt.Color(20, 20, 20)); // FONDO OSCURO
    java.util.List<entidades.Producto> productos = st.getProductos();

    if (st != null && st.getProductos() != null) {
        for (Producto p : st.getProductos()) {
            PanelProducto card = new PanelProducto(p);
            jPanel6.add(card);
        }
    }

    jPanel6.revalidate();
    jPanel6.repaint();
}


   
    
    
    
}

